### PR TITLE
Added new board adaptation: armsom-sige7

### PR DESCRIPTION
**Pull request by Z-Keven**
Hello, the armsom team has added support for armsom-sige7. Tested and verified ok.
For armsom-sige7 related information, please refer to: [https://docs.armsom.org/docs/sbc/sige7/sige7-introduction](url)

### CODE REVIEW

**Comment by Joshua-Riek** [comment]
It looks good. I'll accept the PR when the device tree is merged into the kernel. 

Since there are so many boards now, I need to do a lot of optimization to the build process. This will not affect the Armsom boards, but I do need to make some changes as the build process takes a very long time and I have limited computing power.

**Comment by zhouxp5300747** [comment]
> It looks good. I'll accept the PR when the device tree is merged into the kernel.
> 
> Since there are so many boards now, I need to do a lot of optimization to the build process. This will not affect the Armsom boards, but I do need to make some changes as the build process takes a very long time and I have limited computing power.
OK, I look forward to your optimization of the build process. I'm also very interested in this

**Comment by zhouxp5300747** [comment]
I think it would be more convenient and effective to put these board configuration related information into a file and read the board configuration in the file

**Comment by Joshua-Riek** [comment]
Yeah, I will work on this soon, merging now.

**Pull request merged**
