### PR TITLE
Change recommendation for img burning

### PR DESCRIPTION
**Pull request by EvilOlaf**
Unlike balenaEtcher the USBimager tool does not have sort of a spyware conspiracy attached to it (yet ^^) and is overall more lightweight.
https://news.ycombinator.com/item?id=28158519

### CODE REVIEW

**Comment by watou** [comment]
One data point: off this pull request I went and downloaded the Mac Intel version and found 1) author stopped supporting Mac Intel as of previous version, 2) on my system program was unsigned and therefore hard to get running, and 3) on pressing ... button to load image file, app went unresponsive pinwheel mode and had to be forciby stopped (both instances).  So while the advice to use a leaner imager is sensible, in this case it might lead users to frustration.  Just something to consider.

**Comment by EvilOlaf** [comment]
Hm as for myself I never had any issues with this tool whatsoever, using on both MS Windows and Debian based Linux distros.

It is also the tool that is primarily recommended by Armbian to write images to sd cards. Etcher is sort of fallback. Maybe it is wise to showcase and provide links to both here as well.

**Comment by bagong** [comment]
Add in RPI Imager, which works perfectly fine, even though a bit RPI
centered.

Best

.r.

**Comment by Joshua-Riek** [comment]
This is sad to hear and valid, but USBImager seems less user friendly and may cause confusion among users. So this does give me some pause.

**Review by Joshua-Riek — COMMENTED** [review]
While I do not like Etcher spying, I think its a convenient program, perhaps we should link both Etcher and USBimager?

**Review by Joshua-Riek — APPROVED** [review]

**Pull request merged**
