### PR TITLE
package rkaiq camera engine

### PR DESCRIPTION
**Pull request by peytonicmaster6**
Latest version of the rkaiq camera engine for rk3588 devices. Source code for the package can be found [here](https://github.com/peytonicmaster6/camera-engine-rkaiq.git).

### CODE REVIEW

**Comment by Joshua-Riek** [comment]
I would like to upgrade this but don't have time at the moment to dig through that package. Preferably id like to see the source from rockchip and upload it to Launchpad.

**Comment by peytonicmaster6** [comment]
Source code is stored on Firefly-Linux's Gitlab [here](https://gitlab.com/firefly-linux/external/camera_engine_rkaiq/-/tree/rk356x/linux5.10_release_v1.4.0b?ref_type=tags). There's one slight modification that needs to be made, the rkaiq_3A_server.cpp code isn't updated on that tag and throws segfaults due to multi camera errors. To fix this, use the rkaiq_3A_server.cpp from the [rk3588/linux_release_v1.3.0e](https://gitlab.com/firefly-linux/external/camera_engine_rkaiq/-/blob/rk3588/linux_release_v1.3.0e/rkaiq_3A_server/rkaiq_3A_server.cpp?ref_type=tags) tag.

I would have just used the rk3588/linux_release_v1.3.0e tag entirely, but that rkaiq version is only [v5.0x3.0](https://gitlab.com/firefly-linux/external/camera_engine_rkaiq/-/blob/rk3588/linux_release_v1.3.0e/rkaiq/RkAiqVersion.h?ref_type=tags#L732) while the rk356x/linux5.10_release_v1.4.0b tag is [v5.0x4.1](https://gitlab.com/firefly-linux/external/camera_engine_rkaiq/-/blob/rk356x/linux5.10_release_v1.4.0b/rkaiq/RkAiqVersion.h?ref_type=tags#L744), so I figured I'd go with the newest.

The package I have in this pull request is the compiled code for v5.0x4.1 with the correct rkaiq_3A_server for rk3588 devices. I copied the structure from the existing packages that I was attempting to replace.

**Comment by Joshua-Riek** [comment]
I see thank you, I will still need some time to take a look. I'm currently busy porting the rootfs build process to livecd-rootfs to follow upstream Ubuntu, it's taking some time but the images produced by it are perfect.

**Comment by peytonicmaster6** [comment]
Sounds good! If there's anything other questions or if you need any help from me, just let me know :)

**Comment by Joshua-Riek** [comment]
Sorry for delay in getting back to this, but this needs to be packaged on Launchpad and I would like to find the exact rockchip release tags in correspondence to the 6.1 kernel and 5.10 kernel releases.

**Comment by peytonicmaster6** [comment]
I am working on integrating the source code into Launchpad, which can be found [here](https://git.launchpad.net/~peytonicmaster6/+git/camera_engine_rkaiq?h=jammy-rk3588).

As for the release tags corresponding to kernel 5.10 and kernel 6.1, I know for sure that this [tag](https://gitlab.com/firefly-linux/external/camera_engine_rkaiq/-/tree/rk3588/linux_release_v1.4.0b?ref_type=tags) works with kernel 5.10. It may also work fine with 6.1, but I cannot get cameras to work on kernel 6.1 at all, so I'm unable to test at this time.

**Comment by Joshua-Riek** [comment]
Do you have a list of build deps and build instructions?

**Comment by Joshua-Riek** [comment]
@peytonicmaster6 I started to package the camera engine rkaiq, source code is linked below but i still need to test it out.

https://git.launchpad.net/~jjriek/+git/camera-engine-rkaiq?h=rk3588

**Comment by peytonicmaster6** [comment]
@Joshua-Riek I tried out your launchpad code and it build perfectly! There's only one slight issue, you're pulling outdated tuning files from the source code. The location to the current tuning files is `rkaiq/iqfiles/isp3x`. Once I updated the CmakeLists file and rebuilt, everything worked as intended! I've tested with two cameras running simultaneously and no issues there :)

On another note, there's some externally stored iqfiles that I think people would be interested in, namely the raspberry pi camera ones. Radxa has the tuning files or the V1 and V2 cameras [here](https://github.com/radxa-pkg/rockchip-iqfiles/tree/main/rockchip-iqfiles-rk3588), and the tuning file for the V3 camera can be found [here](https://github.com/peytonicmaster6/rockchip-iq-files/blob/main/rockchip-iqfiles/imx708_arducam-imx708_default.json). I plan on updating the tuning files for the V1 and V2 cameras from the OpenHD [repo](https://github.com/OpenHD/rockchip-iq-files) so that all the tuning files are in one spot.

**Comment by Joshua-Riek** [comment]
Got it, i still need to do some packaging fixes before adding it to my PPA. Also I stumbled across some documentation and I should be able to patch Cheese to work with these cameras.

**Comment by Joshua-Riek** [comment]
@peytonicmaster6 I should have the rkaiq package finished my tomorrow night, your assistance has been extremely helpful and i cant thank you enough!

**Comment by peytonicmaster6** [comment]
Sweet, I look forward to it! Also, I’m happy to help out any way I can, your Ubuntu images have been a lifesaver! 

On another note, could you share the documentation you found for cheese? I’d be interested to take a look at it.

**Comment by Joshua-Riek** [comment]
This PDF has a lot of good information, Cheese is on chapter 6.7.1 or page 33: [Rockchip_Developer_Guide_Debian_EN.pdf](https://github.com/user-attachments/files/15930049/Rockchip_Developer_Guide_Debian_EN.pdf)

**Comment by Joshua-Riek** [comment]
Hmm anyone know if there is any source code for the rkisp? I need to package that as well.

**Comment by peytonicmaster6** [comment]
Try [here](https://gitlab.com/firefly-linux/external/camera_engine_rkisp)

**Comment by Joshua-Riek** [comment]
I saw that firefly repo but it seems so outdated and there are a lot of compile errors. I will try to do some hacking to fix what i can.

**Comment by peytonicmaster6** [comment]
From the PDF you linked, rkisp is 
> The full name is Rockchip Image Signal Processor, image signal processor. Which is mainly used to implement
> camera's 3A effect, suitable for ISP1.X chips, such as RK3288, RK33999...etc

All of the newer processors are using the ISP3x or ISP2x. Are any of the boards your Ubuntu images support RK3288 or RK3399?

**Comment by Joshua-Riek** [comment]
No, ive only worked with RK3588 and RK3566.

**Comment by Joshua-Riek** [comment]
It's so annoying how Rockchp does not provide easy access and open source repositories.

**Comment by peytonicmaster6** [comment]
Gotcha. You shouldn't need to package it up then. I only have the rkaiq package on my system and the cameras work perfectly fine.

**Comment by Joshua-Riek** [comment]
For the Orange Pi cameras the rkisp package seems to be required. I may just hack in the binarys, but i really do not like the idea of it since Ive been putting more effort into doing things properly.

**Comment by peytonicmaster6** [comment]
Are you referring to this one?
https://media.githubusercontent.com/media/Joshua-Riek/ubuntu-rockchip/main/packages/rkaiq/camera_engine_rkisp-v2.2.0_arm64.deb

I only have rkaiq installed on my OPI 5B and am using a OV13855 from orange pi. Also, what's the error you're getting?

P.S. if you want quicker help with debugging/testing, feel free to join the discord I made for camera development. https://discord.gg/XvFJP2UZ

**Comment by Joshua-Riek** [comment]
Closing as the camera engine has been packaged and is now included by default in images.

**Comment by peytonicmaster6** [comment]
Hi @shingoxy, here's the invite link! https://discord.gg/HTCxRd5c

**Comment by shingoxy** [comment]
> Hi @shingoxy, here's the invite link! https://discord.gg/HTCxRd5c

@peytonicmaster6 Thanks~I have joined the channel~My new image sensor could not found iqfile and rkaiq is not working, I am on debugging it.

**Comment by PsiMation** [comment]
> Hi @shingoxy, here's the invite link! https://discord.gg/HTCxRd5c

Hi, Please may I also receive a Discord invite?  I'm also having issues with my Orange Pi 5 Pro + OV13855 camera - using the latest Ubuntu server 24.04LTS from Joshua Riek, but v4l2-ctl --list-devices only shows my USB webcam, not the OrangePi camera

**Comment by peytonicmaster6** [comment]
@PsiMation heres the link. This one shouldn’t expire anymore.

https://discord.gg/XC9jvy4HmT

**Comment by bambooCZ** [comment]
Hello gentleman. I don't get the result here. @Joshua-Riek wrote that rkaiq is preinstalled in rockchip-ubuntu images so I downloaded [ubuntu-24.10-preinstalled-desktop-arm64-rock-5b.img.xz](https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.4.0/ubuntu-24.10-preinstalled-desktop-arm64-rock-5b.img.xz) to extract it into my Arch setup, but no success. Those files are just not there.

So what to do? I experience the "low brightness + green picture" problem mentioned in #288

**Comment by peyton-howe** [comment]
@bambooCZ My guess is they are no longer included in the images to save space. They can be installed from command-line using apt `sudo apt install camera-engine-rkaiq-rk3588`. Given that you're trying to extract it into an Arch setup, I'd recommend you download the [source code](https://git.launchpad.net/~jjriek/+git/camera-engine-rkaiq?h=noble) directly.

**Comment by bambooCZ** [comment]
@peyton-howe thank you for your answer. I just downloaded those [binaries you have linked in this issue](https://github.com/Joshua-Riek/ubuntu-rockchip/pull/690#issue-2227185753) and it worked.

**Pull request closed without merging**
